const prompts = [
  "What was your first impression of me?",
  "What do you think is the hardest part of what I do for a living",
  "What reality show do you think I'm most likely to binge watch? explain.",
  "Do I seem like a cat or dog person?",
  "What do my shoes tell you about me?",
  "Do I seem like more of a creative or analytical type? explain.",
  "How many speeding tickets do you think I've gotten in my life?",
  "Do I seem like someone who would get a name tattooed on myself?",
  "Have you ever been arrested?",
  "What do you think I'm most likely to splurge on?",
  "Finish the sentence: just by looking at you I'd think ____.",
  "What character would I play in a movie?",
  "Who do you think my celebrity crush is?",
  "Do you think I've ever checked an ex's phone for evidence?",
  "What's the first thing you noticed about me?",
  "Do I seem like a coffee or tea person? Sweetened or unsweetened?",
  "What do you think my go to karaoke song is?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "What does my phone wallpaper tell you about me?",
  "Do I look kind? explain.",
  "Do you think I fall in love easily? why or why not?",
  "As a child, what do you think I wanted to be?",
  "Do you think I'm usually early, on time, or late to events? explain.",
  "What subject do you think I thrived in at school? Did I fail any?",
  "What compliment do you think I hear the most?",
  "What fast food restaurant do you think I'm most likely to drive through? What's my order?",
  "What is my body language telling you right now?",
  "Do you think plants thrive or die in my care? explain.",
  "On a scale of 1-10, how messy do you think my car is? 1 being clean 10 complete disaster",
  "Do you think I was popular in school? explain.",
  "Do you think I've ever been fired from a job? If so, what for?",
  "Do you think I intimidate others? why or why not?",
  "How likely am I to go camping? how high maintenance is my set up?",
  "What about me is most strange or unfamiliar to you?",
  "If myspace were still a thing, what would my profile song be?",
  "What about me intrigues you?",
  "What does my style tell you about me?",
  "Do you think I've ever had my heart broken?",
  "Do you think I've been in love?",
  "What is the worst assumption someone has made about you?",
  "What is your defining characteristic?",
  "What's the most pain you've ever been in that wasn't physical?",
  "How are you, really?",
  "What have I tolerated from people in the past that I no longer have space for?",
  "Something that brought a smile to my face this week was ___.",
  "What are you feeling a lot of lately?",
  "What are you currently working through that others don't see?",
  "What was the biggest turning point in your dating life?",
  "What is your heart telling you?",
  "What is your most toxic trait you can admit to?",
  "Who in your life deserves the biggest thank you? Let them know if you can.",
  "What are you overthinking right now?",
  "What did you last relationship teach you about yourself?",
  "What belief about yourself no longer serves you?",
  "What do you need to forgive yourself for?",
  "Who in your life can you be your most vulnerable with?",
  "Which one of your parent's personality traits do you want to keep/let go of?",
  "Dear younger self: ____.",
  "Think of someone you admire. Why did this person come to mind?",
  "Are you lying to yourself about anything?",
  "What's your favorite part of yourself that isn't physical?",
  "What's the hardest part about dating you?",
  "What is something you've learned about yourself this week?",
  "Self love is ___.",
  "What was the lesson in your most recent painful experience?",
  "I know I'm in love when ___.",
  "What's your favorite song lyric you can think of off the top of your head?",
  "What's the best lesson an ex has ever taught you?",
  "Is there anyone who's changed your life but doesn't know it?",
  "When was the last time you felt lucky to be you?",
  "When was the last time you felt most yourself?",
  "What are you most grateful for in this current moment?",
  "What are you still trying to prove to yourself?",
  "What have you been taking for granted lately?",
  "Is there a feeling you miss?",
  "What would your younger self not believe about your life today?",
  "If you could have it your way: Who would you be with? Where would you be? And what would you be doing?",
  "What do you need to hear right now?",
  "What title would you give this chapter in your life?",
  "What dating advice would you give your younger self?",
  "What lesson should you have learned by now?",
  "When was the last time you were able to use your pain to help someone else?",
  "What would you never want to change about yourself?",
  "What question did this past year leave you with?",
  "What about yourself is hardest to admit?",
  "What question are you trying to answer most in your life right now?",
  "Finish the sentences: strangers would describe me as _____. Only I know that I am ______",
  "When you're asked how are you, how often do you answer truthfully?",
  "What is the most unexplainable thing that's ever happened to you?",
  "Describe your perfect day!",
  "Have you changed your mind about anything recently?",
  "What's been the best compliment a stranger has ever given you?",
  "What is a compliment you wish you received more frequently?",
  "What do you crave more of?",
  "What has been your earliest recollection of happiness?",
  "What are you more afraid of, failure or success? And why?",
  "How would you describe the feeling of being in love?",
  "When was the last time you surprised yourself?",
  "What's been your happiest memory this past year?",
  "Do you think the image you have of yourself matches the image people see you as?",
  "If you have, when was the moment you realized you weren't invincible?",
  "What lesson took you the longest to unlearn?",
  "What part of your life works? What part of your life hurts?",
  "What is your 1st love's name and the reason you fell in love with him/her?",
  "If you could get to know someone in your life on a deeper level, who would it be and why?",
  "What is a dream you've let go of?",
  "What is the last thing you lied to your mother about?",
  "Have you ever told someone I love you but didn't mean it?",
  "Why do you think we met?",
  "What do you think my strength is?",
  "What do you think I could teach you?",
  "Who do I remind you of?",
  "What can you be kinder towards yourself for today?",
  "What's one small thing you can do to be a better person this year?",
  "What can we create together?",
  "How would you describe me to a stranger? A friend? Your family?",
  "What about me most surprised you?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "Based on what you know about me, what book would you recommend I read?",
  "What about me is hardest for you to understand?",
  "What do you think I am most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "If we were in a band, what would our name be?",
  "Based on what you know about me, do you have any viewing recommendations?",
  "What do you think my superpower is?",
  "What is a lesson you will take away from our conversation?",
  "How does one earn your vulnerability?",
  "What do you think our most important similarity is?",
  "In one word, how would you describe our conversation?",
  "What answer of mine made you light up?",
  "When this game is over, what will you remember about me?",
  "What parts of yourself do you see in me?",
  "How do you think our personalities would compliment each other?",
  "What do you think my weakness is?",
  "What would make you feel closer to me?",
  "What do you think I fear the most?",
  "What has this conversation taught you about yourself?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "Do you believe everyone has a calling?",
  "What do you want to let go of, if anything?",
  "In one word, describe how you feel right now",
  "What do you wish you knew about other peoples sex lives?",
  "When was the last time something turned you on?",
  "I wish I didn't have to ask for ____.",
  "What do you feel guilty for wanting/not wanting?",
  "When was the last time something turned you off?",
  "Have you ever tried something in the bedroom that you didn't like?",
  "Think about the best sex you've ever had, what stands out?",
  "Do you use sex for anything other than pleasure?",
  "What is your philosophy around sex?",
  "What part does shame play in your sex life?",
  "What kind of sexual partner are you to yourself?",
  "What kind of sexual partner are you to others?",
  "What would you ask for in bed if there were no consequences?",
  "What are you craving in your life right now?",
  "Something I'm working on is ______.",
  "How are you feeling in this current moment?",
  "What's been occupying your mind lately?",
  "What's your anxiety level right now?",
  "What's been inspiring you lately?",
  "Do you like to create or build things?",
  "Last time you exercised.",
  "Is your job fulfilling?",
  "Is there something on your mind that you're hesitant to share with others but would like to?",
  "Have you had enough water today?",
  "Is there someone in your life that adds light?",
  "What is one thing that you love about yourself?",
  "What is a belief about yourself that is most empowering?",
  "What makes you feel most confident?",
  "What is something you keep doing that keeps hurting?",
  "Do you have something in your life that is creating clutter instead of value?",
  "Do you maintain any relationships that are simply draining?",
  "What is a belief that you have about the world that might be holding you back?",
  "What have you learned that you need more of?",
  "Who has shown up for you in the biggest way?",
  "What is something you're now realizing you took for granted?",
  "What is your happiest memory from the past few weeks?",
  "What was the last show you binged?",
  "What is your go to snack?",
  "What are you most excited about tomorrow?",
  "What is one of the most valuable lessons you've learned?",
  "What movie do you wish you've never seen so you could watch it again for the first time?",
  "What is one of the kindest things someone has done for you?",
  "What change do you want to make in your day to day life?",
  "What privileges do you think I have as a ______?",
  "What is one of your greatest fears?",
  "Do you find open communication difficult?",
  "Do you find being honest is difficult?",
  "What stereotypes do you think have been made about you? Are they true?",
  "What qualities do you associated with a good listener?",
  "Is there anything you disagree with your family on?",
  "When was the last time you had a perspective shift?",
  "What did you grow up believing 'beautiful' looked like?",
  "What do you feel when you hear 'Black lives matter'?",
  "Do you have any friends/family that are not the same race as you?",
  "Do you have any LGBTQIA+ friends/family?",
  "What has been your personal experience with the police?",
  "In what way(s) could you become a better listener?",
  "What do you think I'm like in bed?",
  "What's my name in your contacts?",
  "If we had to do one new thing tonight, what would you want it to be?",
  "Do you like sexting?",
  "What is the best text you could ever receive from me?",
  "What's your favorite thing about my appearance so far?",
  "What's your favorite thing about my personality so far?",
  "What's something about you that might surprise me?",
  "How did your upbringing shape your views on politics?",
  "Are you religious/spiritual?",
  "I do/don't vote because ______.",
  "The world needs more _____ and less _____.",
  "Is there a political view you have that you're afraid to share publicly?",
  "How do you feel about Disneyland? Disney Corporation?",
  "Do you like sleeping?",
  "Who’s the most influential person in your life?",
  "What’s the best decision you’ve ever made in your life?",
  "What’s your deepest regret and how can you forgive yourself or make amends?",
  "What interests you about the person sitting across from (or next to you)?",
  "If you could change one thing about the world, what would it be?",
  "What’s your biggest pet peeve?",
  "What’s a red flag about you?",
  "What’s a green flag about you?",
  "What helps you breathe easy?",
  "What’s been the best moment of your life so far?",
  "What’s something the person across from you doesn’t know about you?",
  "If you could teleport to any location, where would it be?",
  "Who do you trust most in life?",
  "What’s the most important characteristic you look for in a partner?",
  "What’s most important to you right now?",
  "Who’s the one who got away?",
  "What’s the first thing that comes to mind when you think of success?",
  "Past or present is there someone you wish you made amends with?",
  "Who is someone you wish was still around?",
  "What’s your worst tendency?",
  "What’s your best quality?",
  "What childhood memory makes you smile?",
  "How do you spend your free time?",
  "What are your hobbies and how did you get into them?",
  "What goal are you working toward right now?",
  "What’s your favorite way to unwind after a hectic day?",
  "If you could visit any place in the world, where would it be and why?",
  "What fear have you overcome, or are you working to overcome?",
  "What insecurities, if any, are you willing to share?",
  "Tell me a cherished achievement, and what did it mean to you?",
  "What values are fundamental to you and why?",
  "What does happiness mean to you?",
  "What steps do you take for personal growth and self-improvement?",
  "How do you handle life’s uncertainties and challenges?",
  "Morning person or night owl?",
  "Do you have any pets?",
  "Are you a jealous person?",
  "How do you like to show your loved ones appreciation?",
  "How do you handle conflicts in a relationship?",
  "How would you define emotional intimacy?",
  "What is your idea of 'building a future together'?",
  "What does becoming your partner mean to you?",
  "If you could instantly become an expert in one subject, what would it be?",
  "How do you think technology will change our lives in the next 20 years?",
  "What's a conspiracy theory you find intriguing, even if you don't believe it?",
  "What's a small act of kindness you'll never forget?",
  "If you could switch lives with anyone for a day, who would it be?",
  "If you could master any musical instrument instantly, which would you choose?",
  "What's a life lesson you learned the hard way?",
  "If you could have a conversation with any animal, which species would you choose?",
  "What's a childhood dream you still hope to achieve?",
  "Have you ever sung karaoke in public?",
  "Have you ever pretended to understand something when you had no clue?",
  "Have you ever forgotten someone’s name immediately after being introduced?",
  "Have you ever walked into a glass door?",
  "Have you ever gotten food poisoning?",
  "Have you ever been on TV?",
  "Have you ever won a contest or competition?",
  "Have you ever fallen down stairs in front of other people?",
  "Have you ever fainted?",
  "Have you ever skinny dipped?",
  "Have you ever been walked in on while hooking up?",
  "Have you ever been in love with someone who didn’t love you back?",
];
const usedPrompts = new Set();
const promptCard = document.getElementById("prompt-card");
const promptTrigger = document.getElementById("prompt-trigger");

function getPrompt() {
  console.log(usedPrompts.size, prompts.length);
  if (usedPrompts.size === prompts.length) {
    promptCard.classList.add("cta");
    promptTrigger.disabled = true;
    promptCard.innerText = "Fresh out of prompts, bud 🤷🏻‍♀️";
    return;
  }

  let index = getRandomNumber();

  while (usedPrompts.has(index)) {
    index = getRandomNumber();
  }

  usedPrompts.add(index);
  promptCard.classList.remove("cta");
  promptCard.innerText = prompts[index];
}

function getRandomNumber() {
  return Math.floor(Math.random() * prompts.length);
}

promptTrigger.addEventListener("click", getPrompt);
